import { fileURLToPath } from "node:url"

const root = fileURLToPath(new URL("..", import.meta.url))
const target = `${root}packages/omo-native/bin/lib/service-auth.generated.js`

export async function buildServiceAuth(check = false): Promise<void> {
  const result = await Bun.build({
    entrypoints: [`${root}packages/omo-opencode/src/cli/service-auth/commands.ts`],
    target: "node", format: "esm", minify: { whitespace: true, syntax: true },
  })
  if (!result.success) throw new Error("Service auth bundle failed", { cause: result.logs })
  const output = result.outputs[0]
  if (!output) throw new Error("Service auth bundle was not produced")
  const text = `// Generated by bun script/build-service-auth.ts; do not edit.\n${await output.text()}`
  if (check) {
    if (!(await Bun.file(target).exists()) || await Bun.file(target).text() !== text) {
      throw new Error("Service auth bundle is stale; run bun script/build-service-auth.ts")
    }
  } else {
    await Bun.write(target, text)
  }
}

if (import.meta.main) {
  await buildServiceAuth(process.argv.includes("--check"))
  console.log("Service auth bundle is current.")
}
